### PR TITLE
Add shadow and corner radius to match iPadOS PIP

### PR DESCRIPTION
**Pull request by jordanhbuiltbyhq**

### CODE REVIEW

**Comment by Kofktu** [comment]
Why don't we add shadow properties to the PIPUsable Protocol and make it applicable?

ex) 

```swift
struct Shadow {
    let offset: CGSize
    let opacity: CGFloat
    let radius: CGFloat
    let cornerRadius: CGFloat
    let conerCurve: 
}

protocol PIPUsable {
    var shadow: Shadow?
}

extension PIPUsable {
    var shadow: Shadow? { nil }
}
```

**Comment by jordanhbuiltbyhq** [comment]
@Kofktu Done! Do you know why a check is failing?

**Comment by jordanhbuiltbyhq** [comment]
@Kofktu Done! A check is failing though due to using the iOS 12 SDK and CALayerCornerCurve is only available for iOS 13. Can that be bumped up?

**Comment by Kofktu** [comment]
@jordanhbuiltbyhq 
You can change the travis.yml file.

osx_image: xcode10 -> xcode11
SDK:"iphone12.0" -> "iphone13.0"

```yml
osx_image: xcode11

env:
- SDK="iphoneos13.0"
```

**Comment by jordanhbuiltbyhq** [comment]
@Kofktu an error is occurring with that change 🤔 

```
xcodebuild: error: Failed to build workspace Example with scheme Example.
631	Reason: A build only device cannot be used to run this target.
632	Recovery suggestion: No supported iOS devices are available. Connect a device to run your application or choose a simulated device as the destination.
633The command "xcodebuild clean build test -workspace Example/Example.xcworkspace -scheme Example -sdk $SDK -configuration Debug -enableCodeCoverage YES CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO | xcpretty -c" exited with 70.
```

**Comment by Kofktu** [comment]
@jordanhbuiltbyhq 
I'll fix it later.
Thank you very much.

**Pull request merged**
